### PR TITLE
Added the HeliumLogger package description in the Logging step

### PR DESCRIPTION
**Pull request by codeOfRobin**
## Motivation and Context

This really trumped me when I was trying to build the example, so I think it'll be useful for everyone else

Issue #555 
## Checklist:

- [x]  I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x]  If applicable, I have updated the documentation accordingly.
- [x]  If applicable, I have added tests to cover my changes.

)

### CODE REVIEW

**Comment by ianpartridge** [comment]
Thanks for your PR! This is a good idea and I would like to merge it. Two things to fix:

1. Please can you remove the *IMPORTANT* marker. All the steps in the tutorial are of equal importance.
2. You should depend on `minor: 9` of HeliumLogger.

Thank you.

**Comment by codeOfRobin** [comment]
Added the changes you suggested @ianpartridge

**Comment by ianpartridge** [comment]
Thank you. Please could you fill out a CLA for your contribution and email it? https://github.com/IBM-Swift/CLA

**Comment by codeOfRobin** [comment]
@ianpartridge Who do I email it to?

**Comment by ianpartridge** [comment]
kweinmeister@us.ibm.com

**Comment by codeOfRobin** [comment]
Filled and sent the CLA @ianpartridge .

**Comment by ianpartridge** [comment]
Thank you @codeOfRobin !

**Pull request merged**
