### PR TITLE
Making sure we get the latest code from Kitura-Build

### PR DESCRIPTION
**Pull request by BDHernand**
## Description
To consolidate logic between travis files and Makefiles to get the latest code for master branch

## Motivation and Context
Updates to makefile were to guarantee that we get the latest master code when we do a make locally.  The changes to to the .travis.yml file were to simplify the before_script section.

## How Has This Been Tested?
Ran the code through Travis CI which builds Kitura on linux and mac.  Also ran a build locally

## Checklist:

- [ ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by ianpartridge** [comment]
I already merged the Travis simplification.  Can we have a separate PR for the git submodule changes?

**Comment by BDHernand** [comment]
Yeah I dont know why it listed that in this pull request.  The files that changed only show what I changed.

**Comment by ianpartridge** [comment]
I see changes to `.travis.yml` too. Did you pull from the remote before adding your new commit?

**Comment by BDHernand** [comment]
let me redo this.  Delete the pull request.  Will clean it up

**Pull request closed without merging**
