### PR TITLE
Router methods grouping for same route

### PR DESCRIPTION
**Pull request by Naithar**
## Description

Added Router Group class that allows setting different methods for same route.

## Motivation and Context

IBM-Swift/Kitura#293

## How Has This Been Tested?

Added tests that cover route grouping for All, Get and Post Requests.

## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by dfirsht** [comment]
Please submit your CLA as soon as possible so we can review this.

**Comment by Naithar** [comment]
Actually I have a question about CLA. Should I fill it by hand, or can i just full it in editor, so it takes less time to finish (I can print it only tomorrow so skipping the printing part would speed things up)?

**Comment by kweinmeister** [comment]
We'll need a copy with your signature, so it's OK to wait until tomorrow. Thanks.

**Comment by Naithar** [comment]
Got it. Thanks.

**Comment by Naithar** [comment]
CLA filled and sent. :)

**Comment by dfirsht** [comment]
@shmuelk Please review.

**Comment by dfirsht** [comment]
Hey @Naithar, we looked at your implementation. However after looking into this ourselves, we found that we could implement this functionality in just a few lines by using a subrouter. Since this gives us less code to maintain, we are not going to accept this PR. Thanks for contribution though, if you want to tackle any other issues feel free to reach out to us.
(See commit 1587cedc8ffc9c0a252235b4aead5e881ce3b416 for our implementation).

**Pull request closed without merging**
