### PR TITLE
CodableRouterDelegate with custom coding options

### PR DESCRIPTION
**Pull request by tib**
## Description

* This pull request implements the details discussed in the following proposal: 
[KIT-0004: Custom JSONEncoder for Codable Routing](https://github.com/IBM-Swift/evolution/pull/10)

## How Has This Been Tested?

Created a new test case to see if a custom coding strategy with delegate works. 
Ran `swift test` and all the test cases have been passed.

### CODE REVIEW

**Comment by EnriqueL8** [comment]
Currently failing on linux

**Comment by tib** [comment]
@EnriqueL8 Now tests should not fail, please check again.

**Comment by EnriqueL8** [comment]
I think it's a good PR and it should get merged. I didn't see the mention above...

**Comment by tib** [comment]
@seabaylea @EnriqueL8 whops I think, I was closing it by accident during some cleanup on my repos...  sorry, feel free to merge it. 👍

**Pull request closed without merging**
