### PR TITLE
Fixed import statement for 'Kitura_TemplateEngine'

### LINKED ISSUE #459: No such module 'KituraTemplateEngine'
Getting this error in `Router.swift` on version 0.13.1. This error only appears in Xcode. When using `swift build` from the command line, the build is successful.

### PR DESCRIPTION
**Pull request by AnthonyMDev**
Closes #459

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
So, after looking at this a little further, by changing the import statement to `import Kitura_TemplateEngine`, the build error goes away in Xcode, but running `swift build` from the command line gives the following error:

`/MyApp/Packages/Kitura-0.13.1/Sources/Kitura/Router.swift:21:8: error: no such module 'Kitura_TemplateEngine'
import Kitura_TemplateEngine`

If I go back to `import KituraTemplateEngine`, it builds fine from the command line, but the Xcode build error comes back.

**Comment by kweinmeister** [comment]
We'll need a fix that works both on the CLI and Xcode.

I haven't researched this thoroughly yet, but I wonder if the empty Package.swift in Kitura-TemplateEngine is triggering an edge case error with `swift build -X`. We have other modules with the Kitura-* naming scheme, but they have a "name" attribute in Package.swift.

**Comment by AnthonyMDev** [comment]
It might be best that we add a name to the package that does not include the hyphen for importing?

**Comment by shmuelk** [comment]
Thanks for your interest in contributing to Kitura.

I have corrected the original issue in a more proper fashion, by adding to Kitura-TemplatingEngine a "proper target" (KituraTemplatingEngine). I simply moved the one source code file to an added directory under Sources.

**Pull request closed without merging**
