### PR TITLE
Change parse logic In accordance with open close principle 

### PR DESCRIPTION
**Pull request by Yoseob**
Change parse logic In accordance with open close principle 
## Description

change valid check from if to guard
in parse function not change code when add other parce function, just append at parserArchiver

## Motivation and Context

If modify or add more parse function, now parse add code like if else, but In accordance OCP not change 
parse code, just implement

## How Has This Been Tested?

print and check data correctly parsed

```swift
import KituraNet
import KituraSys

let router = Router()
router.use(BodyParser())
router.post("/json") {
    request, response, next in
    response.status(HttpStatusCode.OK).send("Hello, World!")
    next()
}

router.post("/text") {
    request, response, next in
    print("text")
    if let body = request.body{
        print(body.asText())
        response.status(HttpStatusCode.OK).send("Hello, World! \n")
    }
    next()
}

router.post("/urlencoded") {
    request, response, next in
    print("urlencoded")
    if let body = request.body {
        var result = ""
        for (k,v) in body.asUrlEncoded()! {
            result += "\(k)=\(v)&"
        }
        response.status(HttpStatusCode.OK).send("Hello, World! \n" + result)
    }
    next()
}

let server = HttpServer.listen(8989, delegate: router)
Server.run()
```
It is Test code able to parse 

## Checklist:

- [o] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [o] If applicable, I have updated the documentation accordingly.
- [o ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by dfirsht** [comment]
Hey sorry about the delay. Can you fix the merge conflicts that this PR now has?

**Comment by Yoseob** [comment]
That's ok. I'm just waiting your response, will fixed comfilcts this problem

**Comment by Yoseob** [comment]
Now fixed conflicts, please review

**Comment by shmuelk** [comment]
Looks OK to me.

**Comment by dfirsht** [comment]
Can you undo your changes to README.md? We can accept after that.

**Comment by Yoseob** [comment]
Not long after the start . It's hard , and thank you.

**Pull request merged**
