### PR TITLE
Updated link for Swift 3 Style Guidelines

### PR DESCRIPTION
**Pull request by KBryan**
The link provided currently has a broken link.

## Description
Updated link to the current one provided on Ray Wenderlich's github page

## Motivation and Context
Link is currrently broken and takes you to a page that doesn't exist anymore

## How Has This Been Tested?
This has been manually tested.
## Checklist:

- [ ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by shmuelk** [comment]
Thanks for catching the problem with the link.

Please:

   1. Submit a signed (CLA)[https://github.com/IBM-Swift/CLA]
   2. Remove the text ", swift3 branch" from the link text.

**Comment by KBryan** [comment]
Ok, I sent a pull request with those changes. I print, sign and email the CLA shortly. Is there any other things you would like to see inside the Code Conventions.md walk through ?

Regards
Kwame

**Comment by shmuelk** [comment]
Once your signed CLA is received, we'll merge your PR.

**Comment by KBryan** [comment]
Hi Shmuel, here’s my signed CLA.

Regards
Kwame

**Comment by shmuelk** [comment]
@KBryan I'm sorry I messed up with the link to the CLA instructions. They are here [CLA](https://github.com/IBM-Swift/CLA).

**Comment by KBryan** [comment]
This looks exactly the same as the one I just sent to you.  Or am I missing something.

Kwame

**Pull request closed without merging**
