### PR TITLE
Enabled FastCGI Support in Kitura

### PR DESCRIPTION
**Pull request by simplepanda**
Enabled FastCGI support in Kitura, including documentation changes to README.md.

## Description
- Updated Kitura.swift to add add an ```addFastCGIServer(onPort port: Int, with delegate: ServerDelegate)``` method to enable FastCGI.
- Added related data structures. 
- Modified the ```run()``` method in Kitura.swift to start any FastCGI servers configured.
- Modified the ```run()``` command to wait on the centralized ```ListenerGroup.waitForListeners``` rather than calling ```HTTPServer.waitForListeners```.

## Motivation and Context
Enables FastCGI support, per #565 

## How Has This Been Tested?
Minimal code changes to Kitura. The underlying FastCGI support has been tested via both test units in IBM-Swift/Kitura-net as well as demo code running on swift.codeandstrings.com (tested with various benchmarking tools with Nginx and Apache talking to Kitura over FastCGI).

Nginx: http://swift.codeandstrings.com
Apache/mod_proxy_fcgi: http://swift.codeandstrings.com:8080

Note: There is a bug in the current version of the FastCGI code in Kitura-net that affects situations where the web server (connecting to Kitura) is serving content on a port other than port 80 or 443. I've already opened a pull request to correct that problem as well, but this one can go in independently / at the same time.

The server at http://swift.codeandstrings.com:8080 is running code that includes both this PR and the Kitura-net PR to correct the port issue.

## Checklist:
- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by simplepanda** [comment]
As with the other PR, if there is anything you need me to do to help get this merged after the CI system is corrected, let me know.

Also, I updated README.md to include a FastCGI section that explains how to enable FastCGI support, but it may be a good idea to add a Wiki page explaining configuration of Nginx and Apache. Thoughts?

**Comment by ianpartridge** [comment]
Hi, this looks good.  I think `README.md` is getting too long and complicated though (we already hope to simplify it). We could either have a wiki page as you suggest, or you could add a `Documentation/FastCGI.md` file. Storing the docs in the repo is probably better as then we get all the benefits of tracking it in git.

**Comment by simplepanda** [comment]
@ianpartridge Sounds good. Are you thinking remove all references to FastCGI in the main README.md and just migrate it all to a file in Documentation/  - or leave a small reference with a link?

**Comment by ianpartridge** [comment]
I think a reference is valuable, with the main content elsewhere. Then you can go into as much detail as you want in `Documentation/FastCGI.md`.

The reference could be a bullet-point in the Features section of `README.md`, linking through?

**Comment by simplepanda** [comment]
@ianpartridge  - I added some documentation as discussed. Can you peruse  ```Documentation/FastCGI.md``` in my PR and suggest any edits?

**Comment by ianpartridge** [comment]
LGTM!

**Comment by simplepanda** [comment]
Thanks @ianpartridge - I'll leave any version tagging update to you in terms of when this gets folded into a release. The dependency on Kitura-net is already satisfied by minor=22 so Package.swift is all good here.

**Pull request merged**
