### PR TITLE
Refactored Kitura-Net HTTPServerDelegate to ServerDelegate

### PR DESCRIPTION
**Pull request by simplepanda**
As the title describes, this is a refactoring / renaming of the HTTPServerDelegate class protocol in Kitura-net to simply ServerDelegate. Changes apply to both Kitura and Kitura-net, both on the master branch.

In relation to #565 - adding FastCGI to Kitura.

## Description
- Pulled HTTPServerDelegate from the HTTPServer class.
- Placed it in it's own file, ServerDelegate.swift in Kitura-net.
- Replaced all uses of HTTPServerDelegate with ServerDelegate system wide. This affects both the Kitura-Net and Kitura projects.

## Motivation and Context
This class will ultimately be used to provide server protocols other than HTTP and will be used by a forthcoming pull request related to adding a FastCGI server implementation to Kitura. For clarity, this refactor makes it obvious that the ServerDelegate handles more than HTTP and moves it out of the HTTPServer class in the process.

## How Has This Been Tested?
Change is relatively trivial in terms of a refactor. Did a full rebuild of current test projects I'm working on and everything builds and runs as always. There is no real code changes here - just renames for the most part.

## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by simplepanda** [comment]
Note that the CI on this pull request will fail until the PR 42 on Kitura-net is accepted (this pull request depends on that one).

**Comment by shmuelk** [comment]
@simplepanda You didn't update the tests, which is why the build is failing on your PR.

**Comment by ianpartridge** [comment]
@shmuelk this one fails because of the API changes to Kitura-net

**Comment by simplepanda** [comment]
@shmuelk  and @ianpartridge  - you're both right! :)

i missed the test suite on this PR, so that's an issue that's now fixed with my past commit and push. 

This will pass tests once IBM-Swift/Kitura-net#42 is merged and tagged I'll have to update Package.swift to reference the new Kitura-net tag that includes those changes when that happens before this really passes, but after that it should be a-ok.

**Comment by ianpartridge** [comment]
OK we'll bump the version on Kitura-net once we've merged that PR, then you can push another commit to this PR to pick it up.

**Comment by shmuelk** [comment]
There should be no need to bump the version in the Package.swift files. We've already bumped the version of Kitura-net to 0.21.0. The Package.swift file for Kitura already references Kitura-net with a majorVersion of 0 and a minor of 21. Once the PR for Kitura-net is merged and tagged as 0.21.X, this PR should build.

**Comment by ianpartridge** [comment]
But as this is a breaking API change, shouldn't it be `0.22.0`?

**Comment by shmuelk** [comment]
@ianpartridge We're early enough in 0.21 that I don't think it matters. Besides 0.22 will be the "release" at the end of this sprint.

**Comment by simplepanda** [comment]
@shmuelk @ianpartridge I can push the next PR to IBM-Swift/Kitura-net pretty quickly (going to factor in IBM-Swift/Kitura-net#43 to my code which shouldn't take long to test).

The actual FastCGI code won't break anything in that it's self-contained if IBM-Swift/Kitura-net#42 is already merged.

**Comment by ianpartridge** [comment]
I guess there is a wider discussion here about how semver plays into our sprints. We're using a mix of time-based versioning and API-based versioning. That's probably OK while we're at 0.x and rapidly releasing new function.

**Comment by simplepanda** [comment]
Is there an overall roadmap for Kitura? Something like what's being built towards in terms of a theoretical 1.0 release? I'm enjoying this project and would be happy to get my hands dirty(er) once my FastCGI updates are in place.

**Comment by ianpartridge** [comment]
We've been starting to discuss informally what `1.0` would mean. No consensus has been reached! We're very interested in hearing any ideas you (or anyone else) has.

My personal view is we need Swift 3 to be released first, but I'm sure there are other requirements too - both functional and non-functional.

**Comment by simplepanda** [comment]
I'd agree on Swift 3 (final) and Xcode 8 (final) being pre-requesites. There is already a lot of flux on within the sub-dependencies as far as toolchain requirements (latest BlueSocket needs toolchain 2016-06-20, for example) and many of the issues being opened against Kitura seem directly related to build questions that are almost invariably toolchain version related.

I tend to be pretty minimalist when it comes to my app server frameworks - I want to be able to define code for an endpoint and connect the app server to a larger stack that's handling static content, HTTP routing, load balancing, encryption, etc (hence my FastCGI work). Kitura already satisfies this for the most part so the meat and potatoes are already there as far as I'm concerned. Maybe that's a 1.0?

I do recognize that many people want many things from their frameworks though.

**Pull request merged**
