### PR TITLE
Added RawBodyParser for BodyParser default parsing method (#908).

### PR DESCRIPTION
**Pull request by jacobvanorder**
`BodyParser` should default a `ParsedBody.raw(Data)` when the `Content-Type` isn't known.

## Description
`BodyParser` has a [`parserMap`](https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/bodyParser/BodyParser.swift#L31-L34) which designates that text-based `Content-Type`s correspond to a specialized parser (e.g., `application/json` -> `JSONBodyParser`).

If the `Content-Type` was not any of those types, it would fall-through and `nil` out the data from the `RouterRequest` instead of storing the raw data in [`.raw(Data)`](https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/bodyParser/ParsedBody.swift#L42) on `ParsedBody`.

I fixed this by following pattern and creating `RawBodyParser` which just slots the data into `.raw(Data)`. `BodyParser` now defaults to passing the RouterRequest body into `RawBodyParser`.

## Motivation and Context
This is in response to [Issue 908](https://github.com/IBM-Swift/Kitura/issues/908). While exploring @rfdickerson's [Kitura Protobuf Sample](https://github.com/IBM-Swift/Kitura-Protobuf-Sample), I notice that `POST`ing did not work when sending a protobuf file. The `RouterRequest`'s body was `nil` not `application/json`. @rfdickerson [assumed](https://github.com/IBM-Swift/Kitura-Protobuf-Sample/commit/0475ab18045593e9d5a0b9fff511ce4c5adf2f8d#diff-c59d9b61114ad3468cfbb3a6a44fa297L59), as I would have, that the body could have been accessed using `.raw(Data)` on the `ParsedBody`. This was not the case.

## How Has This Been Tested?

I wrote a unit test that tests whether raw data being sent passes through the `router` properly and can be accessed using `.raw(Data)`.

I only ran tests locally on Mac OS X since I do not have access to a Linux environment immediately.

This would only have impact on existing code if the end user _knew_ that `BodyParser` would `nil` out the body and wrote against that scenario.

## Checklist:
- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by jacobvanorder** [comment]
Realized the `arc4Random` isn't available on Linux. I'll update shortly.

**Comment by ianpartridge** [comment]
Thanks for your PR! Please don't use random data in the test. It makes recreating any future failures theoretically impossible.

**Comment by jacobvanorder** [comment]
@ianpartridge would a `Data` object filled with zeros be better? The point is that raw data is coming through. Don't care what but just that the length is the same. Should I be testing for something else?

**Comment by ianpartridge** [comment]
If you can test the same thing using just zeroes then please do that :)

**Comment by jacobvanorder** [comment]
@ianpartridge Will do! Thanks!

**Comment by youming-lin** [comment]
All zeros sounds to me like an edge case.... maybe have another test with statically generated random data?

**Comment by jacobvanorder** [comment]
@ianpartridge Updated!

**Comment by ianpartridge** [comment]
Thanks for your work on this, @jacobvanorder!

**Comment by jacobvanorder** [comment]
@ianpartridge I'd love to chip in more. Is there a standard for picking off issues or is it anything that isn't assigned is fair game?

**Comment by ianpartridge** [comment]
Hi @jacobvanorder.  Any issue that isn't assigned is available - let us know if a particular one looks interesting.  Is there a particular area of Kitura that you've been investigating or using?  If you are looking for a standalone feature to work on, we'd love `Kitura-Credentials` to support more providers (currently we have Facebook, Google and GitHub).  How about creating `Kitura-Credentials-Twitter` so Kitura apps can provide login through the [Twitter OAuth API](https://dev.twitter.com/oauth/reference/post/oauth2/token)?

**Comment by jacobvanorder** [comment]
@ianpartridge Thanks for the direction! 

I came to this issue after investigating Protocol Buffers and @rfdickerson's example for a talk I'll be doing in the spring. I've been trying to frame the depth of what I get into concerning Kitura balanced with my time limit for the talk.

I'll take a look at Twitter OAuth and contribute how I can. This has been really fun to delve into and I'm happy to work on something new.

**Comment by ianpartridge** [comment]
Sounds good - let us know how you get on!

**Comment by JohnKnust** [comment]
The information to set a custom Content-Type could be helpful. 
I didn't set it and it the parser will return here ;) 
I use now: "custom/row" and it works well :)	

if let parser = parserMap[contentTypeWithoutParameters] {
            return parser

**Pull request merged**
