### PR TITLE
Link method for RouterResponse

### PR DESCRIPTION
**Pull request by naithar**
## Description

Added ```link``` method for RouterResponse class.

## Motivation and Context

IBM-Swift/Kitura#311

## How Has This Been Tested?

Added a test in TestResponse.swift file that checks received Link header value for both single and multiple links.

## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by dfirsht** [comment]
Hey @naithar, sorry for the delay, we have been discussing this PR internally. The issue is that if you look at the spec for Link (https://tools.ietf.org/html/rfc5988) you can see that it can take in a lot more parameters than ref. After looking at the implementation of Link in JAX, and seeing some PRs for changing Link functionality in Express, we decided that we should support all options. 

Therefore we propose that the Link function will instead take in one link at a time, and have all possible values for link be accepted as nil default optionals.

The new signature will be something like `func link (_ link: String, rel: String? = nil, anchor: String? = nil, title: String? = nil, type: String? = nil, media: String? = nil)`

**Comment by naithar** [comment]
@dfirsht, thanks for the info. I'll change the implementation then.

**Comment by naithar** [comment]
@dfirsht please review

**Comment by dfirsht** [comment]
Looks great! Thanks @naithar

**Pull request merged**
