### PR TITLE
URL query parameters parsing. Subscript for request body.

### PR DESCRIPTION
**Pull request by naithar**
Implements parsing of dictionaries and arrays passed in url encoded body and uses parsed query from Kitura-net.
Also implements a `subscript` access to `.body` of `RouterRequest`

Previous implementation for `query`: IBM-Swift/Kitura#707 and IBM-Swift/Kitura-net#88

## Motivation and Context
IBM-Swift/Kitura#691

Also covers a `subscript` discussion in IBM-Swift/Kitura#820

## How Has This Been Tested?
Added test to `TestQuery` file

## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by naithar** [comment]
I've noticed that `HTTPIncomingMessage` fails with `URLComponents init failed from parsed value: http://localhost:8090/array?q[]=1&q[]=2&q[]=3`

**Comment by naithar** [comment]
@shmuelk please review

**Comment by naithar** [comment]
This PR should probably wait for #904 as `Query` type depends on `URLComponents`

**Comment by naithar** [comment]
@ianpartridge @shmuelk could you please review this one?  
I've switched from regex to range checks.  
Also changed the way values are parsed to the way it's done in `.queryParameters`

**Comment by rolivieri** [comment]
This PR is quite old; I am wondering if some of the recent changes we have merged into the master branch may address some of the points raised here. For instance, proposals 001, 002, and 003 (https://github.com/IBM-Swift/evolution/tree/master/Kitura/Proposals) have been implemented and merged into master. I am thinking we should close this PR unless the author (@naithar) still sees a need for it and would like to rebase and update the code in this PR.

**Comment by naithar** [comment]
I think this PR can be closed since most of it’s features are already implemented and merged in new Kitura release

**Pull request closed without merging**
